### ISSUE TITLE
`No adoptium version` when running 2.1.6 `cs java`

### ISSUE THREAD

**Issue by gauthamnair** [VirtusLab/coursier-m1#79]
Running on an M2 Pro with Mac OS 13.0 I am unable to install jvms with the aarch64 coursier at least for 2.1.6.

Steps to reproduce:

```
$ curl -L -o cs-aarch64-apple-darwin-2.1.6-Virtus.gz https://github.com/VirtusLab/coursier-m1/releases/download/v2.1.6/cs-aarch64-apple-darwin.gz
$ chmod a+x cs-aarch64-apple-darwin-2.1.6-Virtus
$ ./cs-aarch64-apple-darwin-2.1.6-Virtus version
2.1.6
$ ./cs-aarch64-apple-darwin-2.1.6-Virtus java --jvm 8 -version
JVM 8 not found in index: No adoptium version matching '1.8+' found
```

But the same setup works using the x86 binary (I have Rosetta2 emulation going):

```
$ curl -L -o cs-x86_64-apple-darwin-2.1.6-Virtus.gz https://github.com/VirtusLab/coursier-m1/releases/download/v2.1.6/cs-x86_64-apple-darwin.gz
$ gunzip cs-x86_64-apple-darwin-2.1.6-Virtus.gz
$ chmod a+x cs-x86_64-apple-darwin-2.1.6-Virtus
$ ./cs-x86_64-apple-darwin-2.1.6-Virtus java --jvm 8 -version
... installs the first time ...
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.392-b08, mixed mode)
```

We ran into this issue when trying to use the VirtusLab coursier for more recent M1 architecture binaries. https://github.com/pantsbuild/pants/issues/20174 

The aarch64 binary is able to perform other coursier functions without trouble like `resolve` or `fetch`  `org.scalameta::scalafmt-cli:2.4.2`.

**Comment by tgodzik** [comment]
I don't believe there is JDK 8 released for apple M1. I think it starts at 11. At least looking at https://adoptium.net/en-GB/temurin/releases/?os=mac&arch=aarch64&version=8

**Comment by gauthamnair** [comment]
@tgodzik Thank you very much for the prompt reply. This helps a bunch.
